# =============================================================================
# File: kustomization.yaml
# Version: 1
# Path: infra/k8s/base/_namespace/kustomization.yaml
# Description: Kustomize entry for the namespace resource.
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
